/**
 * codealpine api
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClimbingProvidedAnswers } from './climbingProvidedAnswers';
import { ClimbingQuestionnaire } from './climbingQuestionnaire';

export interface ClimbingQuestion { 
    id: number;
    slug: string;
    question: string;
    questionnaire: ClimbingQuestionnaire;
    answers: ClimbingProvidedAnswers;
}