/**
 * codealpine api
 * The codealpine API description
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ClimbingQuestion } from './climbingQuestion';
import { ClimbingQuestionnaireAnalysis } from './climbingQuestionnaireAnalysis';
import { ClimbingQuestionnaireUser } from './climbingQuestionnaireUser';

export interface ClimbingQuestionnaire { 
    id: number;
    slug: string;
    title: string;
    description: string;
    accessRequired: string;
    climbingQuestion: ClimbingQuestion;
    analysis: ClimbingQuestionnaireAnalysis;
    userResponses: ClimbingQuestionnaireUser;
}